export default {
  dashboards: {
    0: { index: 0, name: 'main', tabs: { main: { name: 'main', layout: [] } } },
    1: {
      index: 1,
      name: 'onboards',
      tabs: {
        main: { name: 'main', layout: [] },
        onboards: {
          name: 'All onboards',
          layout: [
            {
              x: 27,
              y: 0,
              w: 9,
              h: 5,
              i: '0',
              name: 'onboard #6',
              component: 'CommonYoutubePlayer',
              props: { videoId: 'YnBAkHpxPk4', muted: true },
              moved: false,
            },
            {
              x: 9,
              y: 0,
              w: 9,
              h: 5,
              i: '1',
              name: 'onboard #7',
              component: 'CommonYoutubePlayer',
              props: { videoId: 'Kch6NbE8L60', muted: true },
              moved: false,
            },
            {
              x: 0,
              y: 15,
              w: 9,
              h: 5,
              i: '2',
              name: 'onboard #33',
              component: 'CommonYoutubePlayer',
              props: { videoId: 'Ef52HmwTeUQ', muted: true },
              moved: false,
            },
            {
              x: 0,
              y: 0,
              w: 9,
              h: 5,
              i: '3',
              name: 'onboard #44',
              component: 'CommonYoutubePlayer',
              props: { videoId: 'f5SwyfqTUiM', muted: true },
              moved: false,
            },
            {
              x: 18,
              y: 0,
              w: 9,
              h: 5,
              i: '4',
              name: 'onboard #2',
              component: 'CommonYoutubePlayer',
              props: { videoId: 'Yn5Gyc5s7GE', muted: true },
              moved: false,
            },
            {
              x: 9,
              y: 15,
              w: 9,
              h: 5,
              i: '5',
              name: 'onboard #44',
              component: 'CommonYoutubePlayer',
              props: { videoId: 'f5SwyfqTUiM', muted: true },
              moved: false,
            },
            {
              x: 0,
              y: 5,
              w: 9,
              h: 5,
              i: '6',
              name: 'onboard #2',
              component: 'CommonYoutubePlayer',
              props: { videoId: 'Yn5Gyc5s7GE', muted: true },
              moved: false,
            },
            {
              x: 36,
              y: 0,
              w: 4,
              h: 3,
              i: '7',
              name: 'onboard #15',
              component: 'CommonYoutubePlayer',
              props: { videoId: 'ZhFk9VZT9_Q', muted: true },
              moved: false,
            },
            {
              x: 27,
              y: 5,
              w: 9,
              h: 5,
              i: '8',
              name: 'onboard #31',
              component: 'CommonYoutubePlayer',
              props: { videoId: 'hXLN3LEpLTw', muted: true },
              moved: false,
            },
            {
              x: 9,
              y: 10,
              w: 9,
              h: 5,
              i: '9',
              name: 'onboard #911',
              component: 'CommonYoutubePlayer',
              props: { videoId: 'BRYmUk8b0MU', muted: true },
              moved: false,
            },
            {
              x: 0,
              y: 10,
              w: 9,
              h: 5,
              i: '10',
              name: 'onboard #1',
              component: 'CommonYoutubePlayer',
              props: { videoId: 'GbZRNOkVeaQ', muted: true },
              moved: false,
            },
            {
              x: 18,
              y: 10,
              w: 9,
              h: 5,
              i: '11',
              name: 'onboard #77',
              component: 'CommonYoutubePlayer',
              props: { videoId: 'p5qKjfx3Coo', muted: true },
              moved: false,
            },
            {
              x: 27,
              y: 10,
              w: 9,
              h: 5,
              i: '12',
              name: 'onboard #831',
              component: 'CommonYoutubePlayer',
              props: { videoId: '9L6457LBcjM', muted: true },
              moved: false,
            },
            {
              x: 18,
              y: 5,
              w: 9,
              h: 5,
              i: '13',
              name: 'onboard #101',
              component: 'CommonYoutubePlayer',
              props: { videoId: 'dy1glQX50hA', muted: true },
              moved: false,
            },
            {
              x: 18,
              y: 15,
              w: 9,
              h: 5,
              i: '14',
              name: 'onboard #110',
              component: 'CommonYoutubePlayer',
              props: { videoId: 'k0kgvIjNgMc', muted: true },
              moved: false,
            },
            {
              x: 9,
              y: 5,
              w: 9,
              h: 5,
              i: '15',
              name: 'onboard #5',
              component: 'CommonYoutubePlayer',
              props: { videoId: 'VPjGOot_Mfc', muted: true },
              moved: false,
            },
            {
              x: 27,
              y: 15,
              w: 9,
              h: 5,
              i: '16',
              name: 'pitlane',
              component: 'CommonYoutubePlayer',
              props: { videoId: 'UHa-kz6AC9g', muted: true },
              moved: false,
            },
          ],
        },
      },
    },
  },
}
