export default {
  dashboards: {
    0: {
      index: 0,
      name: 'Nurburgring 24 - 21:9 1440x3440',
      tabs: {
        1: {
          name: 'onboards',
          layout: [],
        },
        2: {
          name: 'weather',
          layout: [
            {
              x: 0,
              y: 0,
              w: 40,
              h: 28,
              i: '0',
              name: 'weather radar',
              component: 'CommonIFrame',
              props: {
                url: 'https://www.rainviewer.com/map.html?loc=50.3341,6.9427,10&oFa=0&oC=0&oU=0&oCS=1&oF=0&oAP=0&rmt=2&c=1&o=83&lm=0&th=0&sm=1&sn=1',
              },
              moved: false,
            },
          ],
        },
        3: {
          name: 'timing',
          layout: [
            {
              x: 0,
              y: 0,
              w: 16,
              h: 16,
              i: '0',
              name: 'timing screen',
              component: 'CommonIFrame',
              props: {
                style: 'background-color: white;',
                url: 'https://livetiming24.azurewebsites.net/events/50/results',
              },
              moved: false,
            },
            {
              x: 16,
              y: 0,
              w: 16,
              h: 12,
              i: '1',
              name: 'Main stream',
              component: 'CommonYoutubePlayer',
              props: {
                videoId: 'FVjTSBefDjU',
                muted: false,
              },
              moved: false,
            },
            {
              x: 16,
              y: 12,
              w: 5,
              h: 4,
              i: '2',
              name: 'pitlane',
              component: 'CommonYoutubePlayer',
              props: {
                videoId: 'JaZBWqAmgfQ',
                muted: true,
              },
              moved: false,
            },
            {
              x: 21,
              y: 12,
              w: 5,
              h: 4,
              i: '3',
              name: 'onboard #1',
              component: 'CommonYoutubePlayer',
              props: {
                videoId: 'xsF3QBpvIvE',
                muted: true,
              },
              moved: false,
            },
            {
              x: 26,
              y: 12,
              w: 6,
              h: 4,
              i: '4',
              name: 'onboard #44',
              component: 'CommonYoutubePlayer',
              props: {
                videoId: 'Leq41aBGhAE',
                muted: true,
              },
              moved: false,
            },
          ],
        },
        main: {
          name: 'main',
          layout: [
            {
              x: 0,
              y: 0,
              w: 9,
              h: 6,
              i: 'xsF3QBpvIvE',
              name: 'onboard #1',
              component: 'CommonYoutubePlayer',
              props: {
                videoId: 'xsF3QBpvIvE',
                muted: true,
              },
              moved: false,
            },
            {
              x: 27,
              y: 8,
              w: 5,
              h: 4,
              i: 'FoYaUBPYZow',
              name: 'onboard #98',
              component: 'CommonYoutubePlayer',
              props: {
                videoId: 'FoYaUBPYZow',
                muted: true,
              },
              moved: false,
            },
            {
              x: 27,
              y: 12,
              w: 5,
              h: 3,
              i: 'ESvxRkJ9TqQ',
              name: 'onboard #22',
              component: 'CommonYoutubePlayer',
              props: {
                videoId: 'ESvxRkJ9TqQ',
                muted: true,
              },
              moved: false,
            },
            {
              x: 6,
              y: 12,
              w: 6,
              h: 4,
              i: 'nUWd6IIJ0F8',
              name: 'onboard #33',
              component: 'CommonYoutubePlayer',
              props: {
                videoId: 'nUWd6IIJ0F8',
                muted: true,
              },
              moved: false,
            },
            {
              x: 0,
              y: 12,
              w: 6,
              h: 4,
              i: 'Leq41aBGhAE',
              name: 'onboard #44',
              component: 'CommonYoutubePlayer',
              props: {
                videoId: 'Leq41aBGhAE',
                muted: true,
              },
              moved: false,
            },
            {
              x: 0,
              y: 6,
              w: 9,
              h: 6,
              i: 'cemGzGeo4Hs',
              name: 'onboard #5',
              component: 'CommonYoutubePlayer',
              props: {
                videoId: 'cemGzGeo4Hs',
                muted: true,
              },
              moved: false,
            },
            {
              x: 18,
              y: 0,
              w: 9,
              h: 6,
              i: 'sydhn5DZh4c',
              name: 'onboard #3',
              component: 'CommonYoutubePlayer',
              props: {
                videoId: 'sydhn5DZh4c',
                muted: true,
              },
              moved: false,
            },
            {
              x: 9,
              y: 0,
              w: 9,
              h: 6,
              i: 'Sn00OFqkX8k',
              name: 'onboard #15',
              component: 'CommonYoutubePlayer',
              props: {
                videoId: 'Sn00OFqkX8k',
                muted: true,
              },
              moved: false,
            },
            {
              x: 27,
              y: 4,
              w: 5,
              h: 4,
              i: 'nUWd6IIJ0F8',
              name: 'onboard #831',
              component: 'CommonYoutubePlayer',
              props: {
                videoId: 'nUWd6IIJ0F8',
                muted: true,
              },
              moved: false,
            },
            {
              x: 9,
              y: 6,
              w: 9,
              h: 6,
              i: 'nUWd6IIJ0F8',
              name: 'onboard #831',
              component: 'CommonYoutubePlayer',
              props: {
                videoId: 'nUWd6IIJ0F8',
                muted: true,
              },
              moved: false,
            },
            {
              x: 18,
              y: 6,
              w: 9,
              h: 6,
              i: 'EmCbafg0tZE',
              name: 'onboard #11',
              component: 'CommonYoutubePlayer',
              props: {
                videoId: 'EmCbafg0tZE',
                muted: true,
              },
              moved: false,
            },
            {
              x: 27,
              y: 0,
              w: 5,
              h: 4,
              i: 'JaZBWqAmgfQ',
              name: 'pitlane',
              component: 'CommonYoutubePlayer',
              props: {
                videoId: 'JaZBWqAmgfQ',
                muted: true,
              },
              moved: false,
            },
          ],
        },
      },
    },
    1: {
      index: 1,
      name: 'Monza WEC',
      tabs: {
        main: {
          name: 'main',
          layout: [],
        },
      },
    },
  },
}
